# Generated by Django 5.0 on 2024-01-02 05:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0003_remove_category_table_id_category_table_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('img_name', models.CharField(max_length=20)),
                ('feature', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_App.category_table')),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('cust_name', models.CharField(max_length=20)),
                ('cust_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid phone number', message='Phone number must contain only numeric digits.', regex='^\\d+$')])),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_App.category_table')),
            ],
        ),
    ]
