# Generated by Django 5.0 on 2024-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0005_rename_food_food_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_table',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
