# Generated by Django 5.0 on 2024-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0007_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_table',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
