# Generated by Django 5.0 on 2024-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0008_admin_table_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin_table',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
