# Generated by Django 5.0 on 2024-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0009_customer_table_is_admin_alter_admin_table_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_table',
            name='is_admin',
        ),
    ]
