# Generated by Django 5.0 on 2024-01-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0010_remove_customer_table_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_table',
            name='active',
        ),
    ]
