# Generated by Django 5.0 on 2024-01-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0011_remove_category_table_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_table',
            name='active',
        ),
    ]
