# Generated by Django 5.0 on 2024-01-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0012_remove_food_table_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation_table',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_App.customer_table')),
            ],
        ),
    ]
