# Generated by Django 5.0 on 2024-01-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0013_reservation_table'),
    ]

    operations = [
    ]
