# Generated by Django 2.2.28 on 2024-01-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0021_auto_20240112_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_set', to='Home_App.food_table'),
        ),
    ]
