# Generated by Django 2.2.28 on 2024-01-12 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0022_auto_20240112_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='paypal_order_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
