# Generated by Django 2.2.28 on 2024-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0023_ordermodel_paypal_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item_table',
            old_name='cart_item_id',
            new_name='order_item_id',
        ),
        migrations.AddField(
            model_name='order_item_table',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
