# Generated by Django 2.2.28 on 2024-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0024_auto_20240112_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_table',
            name='img_name',
            field=models.CharField(max_length=500),
        ),
    ]
